import Image from 'next/image'
import Link from 'next/link'
import Head from 'next/head'
import Headers from "../components/Header/header"
export default function Download() {
        return (
                <>
                        <Head>
                                <title>Download</title>
                                <meta name="description" content="Generated by create next app" />
                                <meta name="viewport" content="width=device-width, initial-scale=1" />
                        </Head>
                        <>
                                <Headers />
                                <section>
                                        <div class="class">
                                                <main >
                                                        <div class="container">
                                                                <div class="main">
                                                                        <div style={{ "cursor": "pointer;" }} class="part1">
                                                                                <div class="collaction-part">
                                                                                        <span>ترسناک|درام|هیجان انگیز</span>
                                                                                </div>
                                                                                <div style={{ "direction": "rtl;" }} class="name-part ">
                                                                                        <span>دانلود فیلم Fear of Rain 2021</span>
                                                                                </div>
                                                                        </div>
                                                                        <div style={{ "cursor": "pointer;" }} class="part2">
                                                                                <div class="IMDB-part">
                                                                                        <i class="fas fa-star"><big>5.9</big><small>/10</small><span>IMDB</span></i>
                                                                                </div>
                                                                                <div style={{ "direction": "rtl;" }} class="country-part ">
                                                                                        <i class="fas fa-globe"><span>محصول کشور : امریکا</span></i>
                                                                                        <i class="far fa-clock"><span>مدت زمان:92 دقیقه</span></i>
                                                                                </div>
                                                                        </div>
                                                                        <div style={{ "cursor": "pointer;" }} class="part2">
                                                                                <div style={{ "direction": "rtl;" }} class="min-part">
                                                                                        <i class="far fa-clipboard"><span>میزان آراء: 2.112 نفر</span></i>
                                                                                </div>
                                                                                <div style={{ "direction": "rtl;" }} class="pay-part ">
                                                                                        <i class="fas fa-trophy"><span>فروش کلی : ثبت نشده</span></i>
                                                                                </div>
                                                                        </div>
                                                                        <div style={{ "cursor": "pointer;" }} class="part3">
                                                                                <div style={{ "direction": "rtl;" }} class="max-part text-right">
                                                                                        <span>کارگردان : <big>Castille Landon</big></span>
                                                                                        <span>بازیگران : <big>Israel Broussard, Katherine Heigl, Madison Iseman</big></span>
                                                                                </div>
                                                                        </div>
                                                                        <div style={{ "cursor": "pointer;" }} class="part3">
                                                                                <div style={{ "direction": "rtl;" }} class="matn-part text-center">
                                                                                        <span>خلاصه داستان :</span>
                                                                                        <p>یک دختر جوان که در تمام طول زندگی‌اش با بیماری اسکیزوفرنی دست و پنجه نرم کرده است، به محض آنکه نسبت به همسایه خود برای سرقت یک کودک مشکوک می‌شود، می‌بایست با توهمات وحشتناک جدیدی مواجه شود و...</p>
                                                                                </div>
                                                                        </div>
                                                                        <div style={{ "cursor": "pointer;" }} class="part2">
                                                                                <div style={{ "direction": "rtl;" }} class="age-part ">
                                                                                        <span>رده سنی <big>PG-13</big></span>
                                                                                </div>
                                                                                <div style={{ "direction": "rtl;" }} class="number-part">
                                                                                        <span>نمره منتقدین <small>20</small> <big>از 100</big></span>
                                                                                </div>
                                                                        </div>
                                                                        <div style={{ "cursor": "pointer;" }} class="part4">
                                                                                <div class="link text-right">
                                                                                        <span>لینک های دانلود</span>
                                                                                </div>
                                                                                <div class="part-link">
                                                                                        <div class="container mt-4">
                                                                                                <div style={{ "background-color": "#3598DB", "color": "white" }} class="user-info">
                                                                                                        <div class="img-name">
                                                                                                                <i onclick="toggleUserDetails()" class="fas fa-chevron-down"></i>
                                                                                                                <span style={{ "font-weight": "bold", "padding": "10px 0px" }}>لینک های دانلود زبان اصلی</span>
                                                                                                        </div>
                                                                                                        <div class="details">
                                                                                                                <div style={{ "direction": "rtl;" }} class="main-link text-center">
                                                                                                                        <i class="fas fa-cloud-download-alt"><span>کیفیت : <big>BluRay 1080p</big>== <small>انگورد :<span>RARBG</span>==</small><span>حجم : <span> 2.07 GB</span></span></span></i>
                                                                                                                </div>
                                                                                                                <div class="buttom-link">
                                                                                                                        <a href=""><button>کلیک کنید</button></a>
                                                                                                                </div>
                                                                                                        </div>
                                                                                                </div>
                                                                                        </div>
                                                                                        <div class="container mt-4">
                                                                                                <div style={{ "background-color": "#E74D3D", "color": "white;" }} class="user-info2">
                                                                                                        <div class="img-name2">
                                                                                                                <i onclick="toggleUserDetails2()" class="fas fa-chevron-down"></i>
                                                                                                                <span style={{ "font-weight": "bold", "padding": "10px 0px;" }}>لینک های دانلود دوبله</span>
                                                                                                        </div>
                                                                                                        <div class="details2">
                                                                                                                <div style={{ "direction": "rtl;" }} class="main-link text-center">
                                                                                                                        <i class="fas fa-cloud-download-alt"><span>کیفیت : <big>BluRay 1080p</big>== <small>انگورد :<span>RARBG</span>==</small><span>حجم : <span> 2.07 GB</span></span></span></i>
                                                                                                                </div>
                                                                                                                <div class="buttom-link">
                                                                                                                        <a href=""><button>کلیک کنید</button></a>
                                                                                                                </div>
                                                                                                        </div>
                                                                                                </div>
                                                                                        </div>
                                                                                        <div class="container mt-4">
                                                                                                <div style={{ "background-color": "#7B57E2", "color": "white;" }} class="user-info3">
                                                                                                        <div class="img-name3">
                                                                                                                <i onclick="toggleUserDetails3()" class="fas fa-chevron-down"></i>
                                                                                                                <span style={{ "font-weight": "bold", "padding": "10px 0px" }}>لینک های دانلود زیرنویس</span>
                                                                                                        </div>
                                                                                                        <div class="details3">
                                                                                                                <div class="buttom-link2">
                                                                                                                        <a href=""><button>کلیک کنید</button></a>
                                                                                                                </div>
                                                                                                        </div>
                                                                                                </div>
                                                                                        </div>
                                                                                </div>
                                                                        </div>
                                                                </div>
                                                        </div>
                                                </main>
                                        </div>
                                </section>

                        </>
                </>
        )
}
