import Image from 'next/image'
import Link from 'next/link'
import Head from 'next/head'
import Headers from "../components/Header/header"
export default function Download() {
        return (
                <>
                        <Head>
                                <title>Download</title>
                                <meta name="description" content="Generated by create next app" />
                                <meta name="viewport" content="width=device-width, initial-scale=1" />
                        </Head>
                        <>
                                <Headers />
                                <section>
                                        <div className="class">
                                                <main >
                                                        <div className="container">
                                                                <div className="main">
                                                                        <div className="Main-Download">
                                                                                <div className="part1">
                                                                                        <div className="name-part ">
                                                                                                <span>دانلود فیلم Fear of Rain 2021</span>
                                                                                        </div>
                                                                                        <div className="collaction-part">
                                                                                                <span>ترسناک|درام|هیجان انگیز</span>
                                                                                        </div>
                                                                                </div>
                                                                                <div className="part2">
                                                                                        <div className="country-part ">
                                                                                                <i className="fas fa-globe"><span>محصول کشور : امریکا</span></i>
                                                                                                <i className="far fa-clock"><span>مدت زمان:92 دقیقه</span></i>
                                                                                        </div>
                                                                                        <div className="IMDB-part">
                                                                                                <i className="fas fa-star"><big>5.9</big><small>/10</small><span>IMDB</span></i>
                                                                                        </div>
                                                                                </div>
                                                                                <div className="part2">
                                                                                        <div className="pay-part ">
                                                                                                <i className="fas fa-trophy"><span>فروش کلی : ثبت نشده</span></i>
                                                                                        </div>
                                                                                        <div className="min-part">
                                                                                                <i className="far fa-clipboard"><span>میزان آراء: 2.112 نفر</span></i>
                                                                                        </div>
                                                                                </div>
                                                                                <div className="part3">
                                                                                        <div className="max-part text-right">
                                                                                                <span>کارگردان : <big>Castille Landon</big></span>
                                                                                                <span>بازیگران : <big>Israel Broussard, Katherine Heigl, Madison Iseman</big></span>
                                                                                        </div>
                                                                                </div>
                                                                                <div className="part3">
                                                                                        <div className="matn-part text-center">
                                                                                                <span>خلاصه داستان :</span>
                                                                                                <p>یک دختر جوان که در تمام طول زندگی‌اش با بیماری اسکیزوفرنی دست و پنجه نرم کرده است، به محض آنکه نسبت به همسایه خود برای سرقت یک کودک مشکوک می‌شود، می‌بایست با توهمات وحشتناک جدیدی مواجه شود و...</p>
                                                                                        </div>
                                                                                </div>

                                                                                <div className="part2">
                                                                                        <div className="number-part">
                                                                                                <span>نمره منتقدین <small>20</small> <big>از 100</big></span>
                                                                                        </div>
                                                                                        <div className="age-part ">
                                                                                                <span>رده سنی <big>PG-13</big></span>
                                                                                        </div>
                                                                                </div>
                                                                        </div>
                                                                        <div style={{ "cursor": "pointer;" }} className="part4">
                                                                                <div className="link">
                                                                                        <span>لینک های دانلود</span>
                                                                                </div>
                                                                                <div className="part-link">
                                                                                        <div className="container mt-4">
                                                                                                <div style={{ "backgroundColor": "#3598DB", "color": "white" }} className="user-info">
                                                                                                        <div className="img-name">
                                                                                                                <i onclick="toggleUserDetails()" className="fas fa-chevron-down"></i>
                                                                                                                <span style={{ "fontWeight": "bold", "padding": "10px 0px" }}>لینک های دانلود زبان اصلی</span>
                                                                                                        </div>
                                                                                                        <div className="details">
                                                                                                                <div className="main-link text-center">
                                                                                                                        <i className="fas fa-cloud-download-alt"><span>کیفیت : <big>BluRay 1080p</big>== <small>انگورد :<span>RARBG</span>==</small><span>حجم : <span> 2.07 GB</span></span></span></i>
                                                                                                                </div>
                                                                                                                <div className="buttom-link">
                                                                                                                        <a href=""><button>کلیک کنید</button></a>
                                                                                                                </div>
                                                                                                        </div>
                                                                                                </div>
                                                                                        </div>
                                                                                        <div className="container mt-4">
                                                                                                <div style={{ "backgroundColor": "#E74D3D", "color": "white;" }} className="user-info2">
                                                                                                        <div className="img-name2">
                                                                                                                <i onclick="toggleUserDetails2()" className="fas fa-chevron-down"></i>
                                                                                                                <span style={{ "fontWeight": "bold", "padding": "10px 0px;" }}>لینک های دانلود دوبله</span>
                                                                                                        </div>
                                                                                                        <div className="details2">
                                                                                                                <div className="main-link text-center">
                                                                                                                        <i className="fas fa-cloud-download-alt"><span>کیفیت : <big>BluRay 1080p</big>== <small>انگورد :<span>RARBG</span>==</small><span>حجم : <span> 2.07 GB</span></span></span></i>
                                                                                                                </div>
                                                                                                                <div className="buttom-link">
                                                                                                                        <a href=""><button>کلیک کنید</button></a>
                                                                                                                </div>
                                                                                                        </div>
                                                                                                </div>
                                                                                        </div>
                                                                                        <div className="container mt-4">
                                                                                                <div style={{ "backgroundColor": "#7B57E2", "color": "white;" }} className="user-info3">
                                                                                                        <div className="img-name3">
                                                                                                                <i onclick="toggleUserDetails3()" className="fas fa-chevron-down"></i>
                                                                                                                <span style={{ "fontWeight": "bold", "padding": "10px 0px" }}>لینک های دانلود زیرنویس</span>
                                                                                                        </div>
                                                                                                        <div className="details3">
                                                                                                                <div className="buttom-link2">
                                                                                                                        <a href=""><button>کلیک کنید</button></a>
                                                                                                                </div>
                                                                                                        </div>
                                                                                                </div>
                                                                                        </div>
                                                                                </div>
                                                                        </div>
                                                                </div>
                                                        </div>
                                                </main>
                                        </div>
                                </section>

                        </>
                </>
        )
}
