import { CardNetflix } from "../events/events"
import Head from 'next/head'
import Headers from "../components/Header/header"
import Card from '@/components/Card/Card'
export default function HBO() {
        return (
                <>
                        <Head>
                                <title>HBO</title>
                                <meta name="description" content="Generated by create next app" />
                                <meta name="viewport" content="width=device-width, initial-scale=1" />
                                <link rel="icon" href="/HBO.ico" />
                        </Head>
                        <>
                                <Headers />
                                <div className="card-cantainer">
                                        {CardNetflix.map((e) => {
                                                return <Card key={e.id} poster={e.image} summary={e.summary} name={e.name} />
                                        })}
                                </div>
                        </>
                </>
        )
}
