import Head from 'next/head'
import Headers from "../components/Header/header"
import Footer from "../components/Footer/Footer"
import Main from "../components/Main/Main"
import Image from 'next/image'
import Netflex from "./Netflix"
export default function Home() {
  return (
    <>
      <Head>
        <title>Click Film</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Headers />
      <Main />
      <Footer />
    </>
  )
}
