import Image from 'next/image'
import Link from 'next/link'
import Head from 'next/head'
import Headers from "../components/Header/header"
import Card from "../components/Card/Card"
import { CardNetflix } from "../events/events"
export default function Netflex() {
  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Netflix.ico" />
      </Head>
      <>
        <Headers />
        <div className="card-cantainer">
          {CardNetflix.map((e) => {
            return <Card key={e.id} poster={e.image} summary={e.summary} name={e.name} />
          })}
        </div>
      </>
    </>
  )
}
