import Image from 'next/image'
import Link from 'next/link'
import Head from 'next/head'
import Headers from "../components/Header/header"
import Main from '@/components/Main/Main'
import Footer from '@/components/Footer/Footer'
export default function Film() {
        return (
                <>
                        <Head>
                                <title>Serial</title>
                                <meta name="description" content="Generated by create next app" />
                                <meta name="viewport" content="width=device-width, initial-scale=1" />
                                <link rel="icon" href="" />
                        </Head>
                        <>
                                <Headers />
                                <Main />
                                <Footer />

                        </>
                </>
        )
}
